### ISSUE TITLE
Kohya_SS LORA Load config do nothing

### ISSUE THREAD

**Issue by wildcatquebec** [ashleykleynhans/stable-diffusion-docker#17]
Hello Ashleykleynhans,

I wanted to express my gratitude for your outstanding effort. Your Docker template has proven to be an invaluable resource for both software development training and testing purposes. :)

I followed your README on https://hub.docker.com/r/ashleykza/stable-diffusion-webui yesterday. I'm running Ubuntu 22.04 with Portainer 2.19.0, but I executed your installation instructions from the terminal using Docker, just as your installation tutorial suggests.

Everything appears to be working fine, but I've encountered an issue with Koyha_ss. The buttons to load or save configurations don't seem to be functioning; they simply do nothing. I suspect it may be a problem with my browser. I've tried using Firefox, Chrome, and Brave on Linux. I even installed Windows 10 on VirtualBox and tested it on my mobile device, just to confirm that it's not a browser-related issue. Unfortunately, I'm still encountering the same error. I'm at a loss as to why none of the loading buttons are working.
![Screenshot from 2023-09-12 20-17-50](https://github.com/ashleykleynhans/stable-diffusion-docker/assets/46546296/935b8789-1766-451a-b71f-4b5d74d3d515)
Can you help me ?
Thx alot !!

**Comment by ashleykleynhans** [comment]
Kohya_ss does not update anything in the web interface, you have to tail the log file to watch what it is doing.  The `Load` and `Save` buttons do not open file browsers in `--headless` mode.   They require a physical display to be attached, otherwise they result in Tkinter $DISPLAY errors.  You manually need to copy and paste the path and filename into the text box and then press the `Load` or `Save` buttons once its been populated.

**Comment by wildcatquebec** [comment]
Thx alot :) I suppose i must put config file in the workspace directory
I will try this !
